[package]
name = "sequencer-json-rpc"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
sequencer-core = { path = "../sequencer-core" }
sequencer-database = { path = "../sequencer-database" }