[package]
description = "Framework for building a sequencing layer"
edition = "2021"
name = "sequencer-framework"
version = "0.1.0"

[workspace]
members = [
    "sequencer",
    "sequencer-core",
    "sequencer-macros",
]
resolver = "2"
