[workspace]
members = [
    "crates/ssal",
    "seeder",
    "sequencer",
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.73"
chrono = "0.4.38"
futures = "0.3.30"
rand = "0.8.5"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", default-features = false }
toml = "0.8.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"


clap = { version = "4.4.7", features = ["derive"] }
# alloy = { version = "0.1.1", features = ["full", "signer-keystore", "signer-local"] }
alloy = { version = "0.2.0"}
sequencer = { path = "sequencer" }
ssal = { path = "crates/ssal", default-features = false }
pvde = { git = "https://github.com/radiusxyz/pvde", rev="0abc447e775a52ecc5695cf070086fcad9cdaebb"}

# radius-sequencer-sdk = { git = "https://github.com/radiusxyz/radius-sdk-rs", rev="34ef3b93a2833582123f5e963786d820f24eccf0", features = ["liveness-evm"] }

radius-sequencer-sdk = { git = "https://github.com/radiusxyz/radius-sdk-rs", rev="37b31eafb4d007ad9caff98ab2e64a4be556f1f4", features = ["full", "liveness-evm", "validation-eigenlayer"] }