[package]
description = "Framework for building a sequencing layer"
edition = "2021"
name = "sequencer-framework"
version = "0.1.0"

[dependencies]
sequencer-core = { version = "0.1", path = "sequencer-core", optional = true }
sequencer-database = { version = "0.1", path = "sequencer-database", optional = true }
sequencer-http = { version = "0.1", path = "sequencer-http", optional = true }
sequencer-json-rpc = { version = "0.1", path = "sequencer-json-rpc", optional = true }
sequencer-macros = { version = "0.1", path = "sequencer-macros", optional = true }

[workspace]
members = [
    "sequencer-core",
    "sequencer-database",
    "sequencer-http",
    "sequencer-json-rpc",
    "sequencer-macros",
]
resolver = "2"

[features]
default = [
    "core",
    "database",
    "http",
    "json-rpc",
]
core = ["sequencer-core"]
database = ["sequencer-database"]
http = ["sequencer-http"]
json-rpc = ["sequencer-json-rpc"]
macros = ["sequencer-macros"]