[workspace]
members = [
    "crates/block-commitment",
    "crates/database",
    "crates/json-rpc",
    "crates/ssal",
    "seeder/seeder-avs",
    "sequencer/sequencer-avs",
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.73"
block-commitment = { path = "crates/block-commitment" }
database = { path = "crates/database" }
futures = "0.3.30"
json-rpc = { path = "crates/json-rpc" }
rand = "0.8.5"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.117"
ssal = { path = "crates/ssal", default-features = false }
tokio = { version = "1.37.0", default-features = false }
toml = "0.8.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
