[package]
description = "Framework for building a sequencing layer"
edition = "2021"
name = "sequencer-framework"
version = "0.1.0"

[workspace]
members = [
    "sequencer-core",
    "sequencer-database",
    "sequencer-json-rpc",
    "sequencer-macros",
]
resolver = "2"

[dependencies]
sequencer-core = { path = "sequencer-core" }
sequencer-database = { path = "sequencer-database" }
sequencer-json-rpc = { path = "sequencer-json-rpc" }
sequencer-macros = { path = "sequencer-macros" }