[package]
name = "sequencer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sequencer"
path = "src/bin/sequencer.rs"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.4.7", features = ["derive"] }
const-hex = "1.12"
ethers-core = "2.0"
pvde = { git = "https://github.com/radiusxyz/pvde", rev="0abc447e775a52ecc5695cf070086fcad9cdaebb"}
radius-sdk = { git = "https://github.com/radiusxyz/radius-sdk-rs", rev = "1e645cce57dfc6498bf381a702023c9f1aa2d8a5", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.127"
sha3 = "0.10"
skde = { git = "https://github.com/radiusxyz/skde", rev="3549a4da49053394d3f1aef58ddd2ab416585bbb"}
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"