[package]
name = "test-avs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
ssal = { workspace = true, features = ["avs"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }