# Sequencer
database_path = "./radius/database/default_sequencer"
sequencer_rpc_url = ""
# Ethereum
ethereum_rpc_url = "https://ethereum-holesky-rpc.publicnode.com"
ethereum_websocket_url = "wss://ethereum-holesky-rpc.publicnode.com"
signing_key = ""
# SSAL
ssal_contract_address = "0x54B23E63935a09647148c864ecFE292517deb249"
cluster_id = "0x247300e0bf9226bb4adec509501fd388312ccda6624837f4d24eee3d38a4b91d"
seeder_rpc_url = "http://52.79.222.106:3000"
# EigenLayer AVS
delegation_manager_contract_address = "0xA44151489861Fe9e3055d95adC98FbD462B948e7"
stake_registry_contract_address = "0xe8eF3B92EBF4a7b56743abbbB36bf1A824131f23"
avs_directory_contract_address = "0x055733000064333CaDDbC92763c58BF0192fFeBf"
avs_contract_address = "0xc7AE524F4a1853012b7711a91E543668FF20Bc0D"