[package]
name = "json-rpc"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
primitives = { path = "../primitives" }
tower = "0.4.13"
tower-http = { version = "0.4.4", features = ["cors"] }