[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
database = { path = "../database" }
json-rpc = { path = "../json-rpc" }
primitives = { path = "../primitives" }
ssal = { path = "../ssal" }
tokio = { version = "1.37.0", features = ["full"] }