[package]
name = "ssal"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
database = { path = "../database" }
ethers = { version = "2.0", features = ["abigen", "ws"] }
primitives = { path = "../primitives" }
reqwest = { version = "0.12.4", features = ["json"] }
tokio = { version = "1", features = ["net"] }