[package]
name = "ssal"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
ethers = { version = "2.0", features = ["abigen", "ws"], optional = true }
reqwest = { version = "0.12.4", features = ["json"], optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[features]
ethereum = ["ethers", "reqwest", "serde", "serde_json"]