[package]
name = "ssal"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
primitives = { path = "../primitives" }
ethers = { version = "2.0", features = ["abigen", "ws"] }
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.4"
