[package]
name = "ssal"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
database = { workspace = true, optional = true }
ethers = { version = "2.0", features = ["abigen", "ws"], optional = true }
reqwest = { version = "0.12.4", features = ["json"], optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["net"] }

[features]
ethereum = ["database", "ethers", "reqwest"]