[package]
name = "ssal"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
ethers = { version = "2.0", features = ["abigen", "ws"], optional = true }
futures = { workspace = true }
json-rpc = { workspace = true, optional = true }
pin-project = "1.1.5"
serde = { workspace = true, optional = true }

[features]
ethereum = ["ethers", "json-rpc", "serde"]